apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ecommerce
  name: admin-role
rules:
  # Pod Management
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]

  # Service Management
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]

  # Deployment Management
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
